services:
    postgres:
      build: .
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5

    run:
      build: . 
      image: "exercise-5"
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - .:/app
      command: python3 main.py
