services:
  spark-master:
    # image: bitnami/spark:3.5.1
    build: .
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    # command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - .:/app
    networks:
      - my-network

  spark-worker:
    # image: bitnami/spark:3.5.1
    build: .
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    # command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - .:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge